In [1]:
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2019/start/1"
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')

In [3]:
header = soup.find('tr', attrs={'class':'colhead'})

columns = [col.get_text() for col in header.find_all('td')]

final_df = pd.DataFrame(columns=columns)
final_df

Empty DataFrame
Columns: [, PLAYER, YRS, G, GS, CG, SH, IP, H, ER, BB, SO, W, L, SV, ERA]
Index: []

In [4]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2019/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2019_df = final_df
season2019_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Hyun-Jin Ryu,6,29,29,1,1,182.2,160,47,24,163,14,5,0,2.32
1,2,Jacob deGrom,6,32,32,0,0,204.0,154,55,44,255,11,8,0,2.43
2,3,Gerrit Cole,7,33,33,0,0,212.1,142,59,48,326,20,5,0,2.50
3,4,Justin Verlander,15,34,34,2,1,223.0,137,64,42,300,21,6,0,2.58
4,5,Mike Soroka,2,29,29,0,0,174.2,153,52,41,142,13,4,0,2.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,69,Martin Perez,8,32,29,0,0,165.1,184,94,67,135,10,7,0,5.12
69,70,Jakob Junis,3,31,31,0,0,175.1,192,102,58,164,9,14,0,5.24
70,71,Reynaldo Lopez,4,33,33,1,0,184.0,203,110,65,169,10,15,0,5.38
71,72,Yusei Kikuchi,1,32,32,1,1,161.2,195,98,50,116,6,11,0,5.46
72,73,Rick Porcello,11,32,32,0,0,174.1,198,107,45,143,14,12,0,5.52

In [5]:
season2019_df.to_csv('scraped_data/2019_pitching.csv', index=False, sep=',', encoding='utf-8')

In [6]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2018/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2018_df = final_df
season2018_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Jacob deGrom,6,32,32,1,0,217.0,152,41,46,269,10,9,0,1.70
1,2,Blake Snell,4,31,31,0,0,180.2,112,38,64,221,21,5,0,1.89
2,3,Chris Sale,10,27,27,0,0,158.0,102,37,34,237,12,4,0,2.11
3,4,Trevor Bauer,8,28,27,0,0,175.1,134,43,57,221,12,6,1,2.21
4,5,Aaron Nola,5,33,33,0,0,212.1,149,56,58,224,17,6,0,2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,74,Andrew Cashner,10,28,28,0,0,153.0,177,90,65,99,4,15,0,5.29
74,75,Clayton Richard,11,27,27,0,0,158.2,159,94,60,108,7,11,0,5.33
75,76,Dylan Bundy,5,31,31,1,0,171.2,188,104,54,184,8,16,0,5.45
76,77,Felix Hernandez,15,29,28,0,0,155.2,159,96,59,125,8,14,0,5.55
77,78,Lucas Giolito,4,32,32,0,0,173.1,166,118,90,125,10,13,0,6.13

In [7]:
season2018_df.to_csv('scraped_data/2018_pitching.csv', index=False, sep=',', encoding='utf-8')

In [8]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2017/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2017_df = final_df
season2017_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Corey Kluber,9,29,29,5,3,203.2,141,51,36,265,18,4,0,2.25
1,2,Clayton Kershaw,12,27,27,1,0,175.0,136,45,30,202,18,4,0,2.31
2,3,Max Scherzer,12,31,31,2,0,200.2,126,56,55,268,16,6,0,2.51
3,4,Stephen Strasburg,10,28,28,1,1,175.1,131,49,47,204,15,4,0,2.52
4,5,Alex Wood,7,27,25,0,0,152.1,123,46,38,151,16,3,0,2.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,Ian Kennedy,13,30,30,0,0,154.0,143,92,61,131,5,13,0,5.38
71,72,Jeremy Hellickson,10,30,30,0,0,164.0,160,99,47,96,8,11,0,5.43
72,73,Matt Moore,9,32,31,0,0,174.1,200,107,67,148,6,15,0,5.52
73,74,Wade Miley,9,32,32,0,0,157.1,179,98,93,142,8,15,0,5.61
74,75,Jordan Zimmermann,11,29,29,0,0,160.0,204,108,44,103,8,13,0,6.08

In [9]:
season2017_df.to_csv('scraped_data/2017_pitching.csv', index=False, sep=',', encoding='utf-8')

In [10]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2016/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2016_df = final_df
season2016_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Kyle Hendricks,6,31,30,2,1,190.0,142,45,44,170,16,8,0,2.13
1,2,Jon Lester,14,32,32,2,0,202.2,154,55,52,197,19,5,0,2.44
2,3,Noah Syndergaard,5,31,30,0,0,183.2,168,53,43,218,14,9,0,2.60
3,4,Madison Bumgarner,11,34,34,4,1,226.2,178,69,54,251,15,9,0,2.74
4,5,Johnny Cueto,12,32,32,5,2,219.2,195,68,45,198,18,5,0,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,80,Patrick Corbin,7,36,24,0,0,155.2,177,89,66,131,5,13,1,5.15
80,81,Wade Miley,9,30,30,1,1,166.0,187,99,49,137,9,13,0,5.37
81,,Edinson Volquez,14,34,34,0,0,189.1,217,113,76,139,10,11,0,5.37
82,83,James Shields,13,33,33,1,0,181.2,208,118,82,135,6,19,0,5.85
83,84,Anibal Sanchez,14,35,26,0,0,153.1,171,100,53,135,7,13,0,5.87

In [11]:
season2016_df.to_csv('scraped_data/2016_pitching.csv', index=False, sep=',', encoding='utf-8')

In [12]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2015/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2015_df = final_df
season2015_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Zack Greinke,16,32,32,1,0,222.2,148,41,40,200,19,3,0,1.66
1,2,Jake Arrieta,10,33,33,4,3,229.0,150,45,48,236,22,6,0,1.77
2,3,Clayton Kershaw,12,33,33,4,3,232.2,163,55,42,301,16,7,0,2.13
3,4,David Price,12,32,32,3,1,220.1,190,60,47,225,18,5,0,2.45
4,5,Dallas Keuchel,8,33,33,3,2,232.0,185,64,51,216,20,8,0,2.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,Anibal Sanchez,14,25,25,1,1,157.0,152,87,49,138,10,10,0,4.99
84,,Chris Tillman,10,31,31,0,0,173.0,176,96,64,120,11,11,0,4.99
85,86,Alfredo Simon,9,31,31,2,1,187.0,201,105,68,117,13,12,0,5.05
86,87,Drew Hutchison,5,30,28,1,1,150.1,179,93,44,129,13,5,0,5.57
87,88,Kyle Lohse,16,37,22,0,0,152.1,180,99,43,108,5,13,2,5.85

In [13]:
season2015_df.to_csv('scraped_data/2015_pitching.csv', index=False, sep=',', encoding='utf-8')

In [14]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2014/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2014_df = final_df
season2014_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Clayton Kershaw,12,27,27,6,2,198.1,139,39,31,239,21,3,0,1.77
1,2,Felix Hernandez,15,34,34,0,0,236.0,170,56,46,248,15,6,0,2.14
2,3,Chris Sale,10,26,26,2,0,174.0,129,42,39,208,12,4,0,2.17
3,4,Johnny Cueto,12,34,34,4,2,243.2,169,61,65,242,20,9,0,2.25
4,5,Adam Wainwright,14,32,32,5,3,227.0,184,60,50,179,20,9,0,2.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,98,Travis Wood,8,31,31,0,0,173.2,190,97,76,146,8,13,0,5.03
98,99,Colby Lewis,11,29,29,2,1,170.1,211,98,48,133,10,14,0,5.18
99,100,Clay Buchholz,13,28,28,2,2,170.1,182,101,54,132,8,11,0,5.34
100,101,Ricky Nolasco,12,27,27,1,0,159.0,203,95,38,115,6,12,0,5.38
101,102,Kevin Correia,13,32,26,0,0,154.0,191,93,40,79,7,17,0,5.44

In [15]:
season2014_df.to_csv('scraped_data/2014_pitching.csv', index=False, sep=',', encoding='utf-8')

In [16]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2013/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2013_df = final_df
season2013_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Clayton Kershaw,12,33,33,3,2,236.0,164,48,52,232,16,9,0,1.83
1,2,Jose Fernandez,4,28,28,0,0,172.2,111,42,58,187,12,6,0,2.19
2,3,Matt Harvey,7,26,26,1,1,178.1,135,45,31,191,9,5,0,2.27
3,4,Anibal Sanchez,14,29,29,1,1,182.0,156,52,54,202,14,8,0,2.57
4,5,Zack Greinke,16,28,28,1,1,177.2,152,52,46,148,15,4,0,2.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,91,Jeremy Hellickson,10,32,31,0,0,174.0,185,100,50,135,12,10,0,5.17
91,92,Mike Pelfrey,12,29,29,0,0,152.2,184,88,53,101,5,13,0,5.19
92,93,Joe Saunders,10,32,32,2,0,183.0,232,107,61,107,11,16,0,5.26
93,94,Edinson Volquez,14,33,32,0,0,170.1,193,108,77,142,9,12,0,5.71
94,95,Lucas Harrell,7,36,22,0,0,153.2,174,100,88,89,6,17,0,5.86

In [17]:
season2013_df.to_csv('scraped_data/2013_pitching.csv', index=False, sep=',', encoding='utf-8')

In [18]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2012/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2012_df = final_df
season2012_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Clayton Kershaw,12,33,33,2,2,227.2,170,64,63,229,14,9,0,2.53
1,2,David Price,12,31,31,2,1,211.0,173,60,59,205,20,5,0,2.56
2,3,Justin Verlander,15,33,33,6,1,238.1,192,70,60,239,17,8,0,2.64
3,4,R.A. Dickey,15,34,33,5,3,233.2,192,71,54,230,20,6,0,2.73
4,5,Johnny Cueto,12,33,33,2,0,217.0,205,67,49,170,19,9,0,2.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,Francisco Liriano,14,34,28,0,0,156.2,143,93,87,167,6,12,0,5.34
95,96,Ubaldo Jimenez,12,31,31,0,0,176.2,190,106,95,143,9,17,0,5.40
96,97,Randy Wolf,16,30,26,0,0,157.2,196,99,52,104,5,10,0,5.65
97,98,Luke Hochevar,9,32,32,2,1,185.1,202,118,61,144,8,16,0,5.73
98,99,Ricky Romero,5,32,32,1,0,181.0,198,116,105,124,9,14,0,5.77

In [19]:
season2012_df.to_csv('scraped_data/2012_pitching.csv', index=False, sep=',', encoding='utf-8')

In [20]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2011/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2011_df = final_df
season2011_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Clayton Kershaw,12,33,33,5,2,233.1,174,59,54,248,21,5,0,2.28
1,2,Johnny Cueto,12,24,24,3,1,156.0,123,40,47,104,9,5,0,2.31
2,3,Roy Halladay,16,32,32,8,1,233.2,208,61,35,220,19,6,0,2.35
3,4,Cliff Lee,13,32,32,6,6,232.2,197,62,42,238,17,8,0,2.40
4,,Justin Verlander,15,34,34,4,2,251.0,174,67,57,250,24,5,0,2.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,103,Brian Duensing,10,32,28,1,1,161.2,193,94,52,115,9,14,0,5.23
103,104,Roberto Hernandez,11,32,32,0,0,188.2,205,110,60,109,7,15,0,5.25
104,105,Brad Penny,14,31,31,0,0,181.2,222,107,62,74,11,11,0,5.30
105,106,J.A. Happ,13,28,28,0,0,156.1,157,93,83,134,6,15,0,5.35
106,107,John Lackey,15,28,28,0,0,160.0,203,114,56,108,12,12,0,6.41

In [21]:
season2011_df.to_csv('scraped_data/2011_pitching.csv', index=False, sep=',', encoding='utf-8')

In [22]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2010/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2010_df = final_df
season2010_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Felix Hernandez,15,34,34,6,1,249.2,194,63,70,232,13,12,0,2.27
1,2,Josh Johnson,9,28,28,1,0,183.2,155,47,48,186,11,6,0,2.30
2,3,Clay Buchholz,13,28,28,1,1,173.2,142,45,67,120,17,7,0,2.33
3,4,Adam Wainwright,14,33,33,5,2,230.1,186,62,56,213,20,11,0,2.42
4,5,Roy Halladay,16,33,33,9,4,250.2,231,68,30,219,21,10,0,2.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,98,Javier Vazquez,14,31,26,0,0,157.1,155,93,65,121,10,10,0,5.32
98,99,Kyle Davies,8,32,32,1,0,183.2,206,109,80,126,8,12,0,5.34
99,100,Nick Blackburn,6,28,26,1,0,161.0,194,97,40,68,10,12,0,5.42
100,101,Jeremy Bonderman,9,30,29,0,0,171.0,187,105,60,112,8,10,0,5.53
101,102,Zach Duke,15,29,29,0,0,159.0,212,101,51,96,8,15,0,5.72

In [23]:
season2010_df.to_csv('scraped_data/2010_pitching.csv', index=False, sep=',', encoding='utf-8')

In [24]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2009/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2009_df = final_df
season2009_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Zack Greinke,16,33,33,6,3,229.1,195,55,51,242,16,8,0,2.16
1,2,Chris Carpenter,15,28,28,3,1,192.2,156,48,38,144,17,4,0,2.24
2,3,Tim Lincecum,10,32,32,4,2,225.1,168,62,68,261,15,7,0,2.48
3,4,Felix Hernandez,15,34,34,2,1,238.2,200,66,71,217,19,5,0,2.49
4,5,Jair Jurrjens,8,34,34,0,0,215.0,186,62,75,152,14,10,0,2.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,83,Braden Looper,12,34,34,0,0,194.2,226,113,64,100,14,7,0,5.22
83,84,Jeff Suppan,17,30,30,0,0,161.2,200,95,74,80,7,12,0,5.29
84,85,Brian Tallet,9,37,25,0,0,160.2,169,95,72,120,7,9,0,5.32
85,86,Livan Hernandez,17,31,31,2,0,183.2,220,111,67,102,9,12,0,5.44
86,87,Brian Moehler,14,29,29,1,0,154.2,187,94,51,91,8,12,0,5.47

In [25]:
season2009_df.to_csv('scraped_data/2009_pitching.csv', index=False, sep=',', encoding='utf-8')

In [26]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2008/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2008_df = final_df
season2008_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Johan Santana,12,34,34,3,2,234.1,206,66,63,206,16,7,0,2.53
1,2,Cliff Lee,13,31,31,4,2,223.1,214,63,34,170,22,3,0,2.54
2,3,Tim Lincecum,10,34,33,2,1,227.0,182,66,84,265,18,5,0,2.62
3,4,CC Sabathia,19,35,35,10,5,253.0,223,76,59,251,17,10,0,2.70
4,5,Roy Halladay,16,34,33,9,2,246.0,220,76,39,206,20,11,0,2.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,Brian Bannister,5,32,32,1,0,182.2,215,117,58,113,9,16,0,5.76
95,96,Brandon Backe,8,31,31,0,0,166.2,202,112,77,127,9,14,0,6.05
96,,Livan Hernandez,17,31,31,2,0,180.0,257,121,43,67,13,11,0,6.05
97,98,Nate Robertson,9,32,28,0,0,168.2,218,119,62,108,7,11,0,6.35
98,99,Carlos Silva,9,28,28,1,0,153.1,213,110,32,69,4,15,0,6.46

In [27]:
season2008_df.to_csv('scraped_data/2008_pitching.csv', index=False, sep=',', encoding='utf-8')

In [28]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2007/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2007_df = final_df
season2007_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Jake Peavy,15,34,34,0,0,223.1,169,63,68,240,19,6,0,2.54
1,2,Brandon Webb,7,34,34,4,3,236.1,209,79,72,194,18,10,0,3.01
2,,John Lackey,15,33,33,2,2,224.0,219,75,52,179,19,9,0,3.01
3,4,Brad Penny,14,33,33,0,0,208.0,199,70,73,135,16,4,0,3.03
4,5,Roberto Hernandez,11,32,32,2,1,215.0,199,73,61,137,19,8,0,3.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,88,Jose Contreras,11,32,30,2,2,189.0,232,117,62,113,10,17,0,5.57
88,89,Kip Wells,12,34,26,0,0,162.2,186,103,78,122,7,17,0,5.70
89,90,Edwin Jackson,17,32,31,1,1,161.0,195,103,88,128,5,15,0,5.76
90,91,Scott Olsen,6,33,33,0,0,176.2,226,114,85,133,10,15,0,5.81
91,92,Adam Eaton,10,30,30,0,0,161.2,192,113,71,97,10,10,0,6.29

In [29]:
season2007_df.to_csv('scraped_data/2007_pitching.csv', index=False, sep=',', encoding='utf-8')

In [30]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2006/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2006_df = final_df
season2006_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Johan Santana,12,34,34,1,0,233.2,186,72,47,245,19,6,0,2.77
1,2,Roy Oswalt,13,33,32,2,0,220.2,220,73,38,166,15,8,0,2.98
2,3,Chris Carpenter,15,32,32,5,3,221.2,194,76,43,184,15,8,0,3.09
3,4,Josh Johnson,9,31,24,0,0,157.0,136,54,68,133,12,7,0,3.10
4,,Brandon Webb,7,33,33,5,3,235.0,216,81,50,178,16,8,0,3.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,88,Jeff Weaver,11,31,31,0,0,172.0,213,110,47,107,8,14,0,5.76
88,89,Rodrigo Lopez,11,36,29,0,0,189.0,234,124,59,136,9,18,0,5.90
89,90,Carlos Silva,9,36,31,0,0,180.1,246,119,32,70,11,15,0,5.94
90,91,Jason Marquis,15,33,33,0,0,194.1,221,130,75,96,14,16,0,6.02
91,92,Joel Pineiro,12,40,25,1,0,165.2,209,117,64,87,8,13,1,6.36

In [31]:
season2006_df.to_csv('scraped_data/2006_pitching.csv', index=False, sep=',', encoding='utf-8')

In [32]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2005/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2005_df = final_df
season2005_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Roger Clemens,24,32,32,1,0,211.1,151,44,62,185,13,8,0,1.87
1,2,Andy Pettitte,18,33,33,0,0,222.1,188,59,41,171,17,9,0,2.39
2,3,Dontrelle Willis,9,34,34,7,5,236.1,213,69,55,170,22,10,0,2.63
3,4,Pedro Martinez,18,31,31,4,1,217.0,159,68,47,208,15,8,0,2.82
4,5,Chris Carpenter,15,33,33,7,4,241.2,204,76,51,213,21,5,0,2.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,101,Zack Greinke,16,33,33,2,0,183.0,233,118,53,114,5,17,0,5.80
101,102,Mark Hendrickson,10,31,31,1,0,178.1,227,117,49,89,11,8,0,5.90
102,103,Joe Kennedy,7,35,24,0,0,152.2,192,102,64,97,8,13,0,6.01
103,104,Eric Milton,11,34,34,0,0,186.1,237,134,52,123,8,15,0,6.47
104,105,Jose Lima,13,32,32,1,0,168.2,219,131,61,80,5,16,0,6.99

In [33]:
season2005_df.to_csv('scraped_data/2005_pitching.csv', index=False, sep=',', encoding='utf-8')

In [34]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2004/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2004_df = final_df
season2004_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Jake Peavy,15,27,27,0,0,166.1,146,42,53,173,15,6,0,2.27
1,2,Randy Johnson,22,35,35,4,2,245.2,177,71,44,290,16,14,0,2.60
2,3,Johan Santana,12,34,34,1,1,228.0,156,66,54,265,20,6,0,2.61
3,4,Ben Sheets,10,34,34,5,0,237.0,201,71,32,264,12,14,0,2.70
4,5,Carlos Zambrano,12,31,31,1,1,209.2,174,64,81,188,16,8,0,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,90,Brian Anderson,13,35,26,2,1,166.0,217,104,53,70,6,12,0,5.64
90,91,Esteban Loaiza,14,31,27,2,1,183.0,217,116,71,117,10,7,0,5.70
91,92,Shawn Estes,13,34,34,1,0,202.0,223,131,105,117,15,8,0,5.84
92,93,Scott Elarton,10,29,29,1,1,158.2,164,104,62,103,3,11,0,5.90
93,94,Jose Acevedo,5,39,27,0,0,157.2,188,104,45,117,5,12,0,5.94

In [35]:
season2004_df.to_csv('scraped_data/2004_pitching.csv', index=False, sep=',', encoding='utf-8')

In [36]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2003/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2003_df = final_df
season2003_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Pedro Martinez,18,29,29,3,0,186.2,147,46,47,206,14,4,0,2.22
1,2,Jason Schmidt,14,29,29,5,3,207.2,152,54,46,208,17,5,0,2.34
2,3,Kevin Brown,19,32,32,0,0,211.0,184,56,56,185,14,9,0,2.39
3,4,Mark Prior,5,30,30,3,1,211.1,183,57,50,245,18,6,0,2.43
4,5,Tim Hudson,17,34,34,3,2,240.0,197,72,61,162,16,7,0,2.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,97,Jeremy Bonderman,9,33,28,0,0,162.0,193,100,58,108,6,19,0,5.56
97,98,Mike Maroth,6,33,33,1,0,193.1,231,123,50,87,9,21,0,5.73
98,,Shawn Estes,13,29,28,1,1,152.1,182,97,83,103,8,11,0,5.73
99,100,Cory Lidle,9,31,31,2,0,192.2,216,123,60,112,12,15,0,5.75
100,101,Jeff Weaver,11,32,24,0,0,159.1,211,106,47,93,7,9,0,5.99

In [37]:
season2003_df.to_csv('scraped_data/2003_pitching.csv', index=False, sep=',', encoding='utf-8')

In [38]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2002/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2002_df = final_df
season2002_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Pedro Martinez,18,30,30,2,0,199.1,144,50,40,239,20,4,0,2.26
1,2,Randy Johnson,22,35,35,8,4,260.0,197,67,71,334,24,5,0,2.32
2,3,Derek Lowe,17,32,32,1,1,219.2,166,63,48,127,21,8,0,2.58
3,4,Greg Maddux,23,34,34,0,0,199.1,194,58,45,118,16,6,0,2.62
4,5,Barry Zito,15,35,35,1,0,229.1,182,70,78,182,23,5,0,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Brandon Duckworth,8,30,29,0,0,163.0,167,98,69,167,8,9,0,5.41
89,90,Steve W. Sparks,9,32,30,3,0,189.0,238,116,67,98,8,16,0,5.52
90,91,Scott Erickson,15,29,28,3,1,160.2,192,99,68,74,5,12,0,5.55
91,92,Esteban Loaiza,14,25,25,3,1,151.1,192,96,38,87,9,10,0,5.71
92,93,Mike Hampton,16,30,30,0,0,178.2,228,122,91,74,7,15,0,6.15

In [39]:
season2002_df.to_csv('scraped_data/2002_pitching.csv', index=False, sep=',', encoding='utf-8')

In [40]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2001/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2001_df = final_df
season2001_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Randy Johnson,22,35,34,3,2,249.2,181,69,71,372,21,6,0,2.49
1,2,Curt Schilling,20,35,35,6,1,256.2,237,85,39,293,22,6,0,2.98
2,3,John Burkett,15,34,34,1,1,219.1,187,74,70,187,12,12,0,3.04
3,4,Greg Maddux,23,34,34,3,3,233.0,220,79,27,173,17,11,0,3.05
4,,Freddy Garcia,15,34,34,4,3,238.2,199,81,69,163,18,6,0,3.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,90,Chris Holt,5,30,22,1,0,151.1,197,97,57,80,7,9,0,5.77
90,91,Jose Mercedes,8,33,31,2,0,184.0,219,119,63,123,8,17,0,5.82
91,92,Darren Oliver,20,28,28,1,0,154.0,189,103,65,104,11,11,0,6.02
92,93,Dave Mlicki,10,34,29,0,0,167.2,203,115,74,97,11,11,0,6.17
93,94,Dave Burba,15,32,27,1,0,150.2,188,104,54,118,10,10,0,6.21

In [41]:
season2001_df.to_csv('scraped_data/2001_pitching.csv', index=False, sep=',', encoding='utf-8')

In [42]:
final_df =pd.DataFrame(columns=final_df.columns)
for i in range(1,500,50):

    url = "https://www.espn.com/mlb/history/leaders/_/type/pitching/breakdown/season/year/2000/start/{}".format(i)
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:

        stats = [stat.get_text() for stat in player.find_all('td')]

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        final_df = pd.concat([final_df, temp_df], ignore_index=True)

season2000_df = final_df
season2000_df

,,PLAYER,YRS,G,GS,CG,SH,IP,H,ER,BB,SO,W,L,SV,ERA
0,1,Pedro Martinez,18,29,29,7,4,217.0,128,42,32,284,18,6,0,1.74
1,2,Kevin Brown,19,33,33,5,1,230.0,181,66,47,216,13,6,0,2.58
2,3,Randy Johnson,22,35,35,8,3,248.2,202,73,76,347,19,7,0,2.64
3,4,Jeff C. D'Amico,8,23,23,1,1,162.1,143,48,46,101,12,7,0,2.66
4,5,Greg Maddux,23,35,35,6,3,249.1,225,83,42,190,19,9,0,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,94,Pat Rapp,10,31,30,0,0,174.0,203,114,83,106,9,12,0,5.90
94,95,Omar Daal,11,32,28,0,0,167.0,208,114,72,96,4,19,0,6.14
95,96,Chris Carpenter,15,34,27,2,0,175.1,204,122,83,113,10,12,0,6.26
96,97,Jose Lima,13,33,33,0,0,196.1,251,145,68,124,7,16,0,6.65
97,98,David Cone,17,30,29,0,0,155.0,192,119,82,120,4,14,0,6.91

In [43]:
season2000_df.to_csv('scraped_data/2000_pitching.csv', index=False, sep=',', encoding='utf-8')